name: Test

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    name: "Test"
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Files
      uses: actions/checkout@v2

    - name: Build and Install
      run: docker-compose build --no-cache

    - name: Run Tests
      run: make tests
